export const API_BASE_URL = "https://movienew.cybersoft.edu.vn/api";
export const TOKEN_CYBERSOFT =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZW5Mb3AiOiJCb290Y2FtcCA4MiIsIkhldEhhblN0cmluZyI6IjIwLzExLzIwMjUiLCJIZXRIYW5UaW1lIjoiMTc2MzU5NjgwMDAwMCIsIm5iZiI6MTczNDMwNzIwMCwiZXhwIjoxNzYzNzY5NjAwfQ.0FVjgESRWQdgV5umKdlAzdQ0ru01kk_ZfAzIVuecN28";
export const USER_LOCAL_STORAGE = "userLogin";
